### ISSUE TITLE
Website unavailable?

### ISSUE THREAD

**Issue by MengelCode** [DevvitIO/Multiplayer-Hangman#60]
Hello everyone,
it is just me or does it seem to be both the case that:
1.) The website (assuming it was once hosting the game itself) is no longer there?
2.) The project has been abandoned?

I am on search for multiplayer games I can play together with my closed-off community online.

Have a good time, whoever is reading that.

**Comment by Tor020** [comment]
Previously the domain name was deployed via github pages.

There was a setup where since github repo was hosted by github pages it fit to have all associated projects subdomained through github, this is no longer the case. Netlify is used for deployment.

I'll take the live page off the github repo. Sorry for the confusion.
